### ISSUE TITLE
error in docker

### ISSUE THREAD

**Issue by shengchenyang** [TheFalloutOf76/CDP-bug-MouseEvent-.screenX-.screenY-patcher#3]
Write the following code based on DrissionPage_example.py:

```python
from DrissionPage import Chromium, ChromiumOptions
from sys import platform
import time
import os

co = ChromiumOptions()
co.set_local_port(9222)
co.set_timeouts(base=1)

# change this to the path of the folder containing the extension
EXTENSION_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "turnstilePatch"))
co.add_extension(EXTENSION_PATH)

co.headless()
if platform == "linux" or platform == "linux2":
    platformIdentifier = "X11; Linux x86_64"
elif platform == "darwin":
    platformIdentifier = "Macintosh; Intel Mac OS X 10_15_7"
elif platform == "win32":
    platformIdentifier = "Windows NT 10.0; Win64; x64"

co.set_user_agent(
    f"Mozilla/5.0 ({platformIdentifier}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36")
co.set_argument("--no-sandbox")

browser = Chromium(co)
browser.clear_cache(cookies=True)
page = browser.get_tabs()[-1]
url = "https://www.dogalecza.com.tr/selfish-drop-cilt-bakimi-2913?ttclid=E_C_P_CscBCl2ZJ5wkz8R7QIa1piD55ZM8JYXCDoOa7wRFOHpqjQs3txTqaEkaQxXL5uYUNmmeRvb58jEdsKvmu0v23IVK1CF84csU2VTLa23pObxOzm5kzUkH7oW7nZzSBl9u8aTQgRN5xd427Mg0XDVsPxj5If5Tw2utodBUcY_nVohK-73lsz9wzgwKblGPOqZizZjapSASoPy0XDtfyYFJF4t2luQy6q0FVp16UPSXbmkk-XZOKdTCDz9e1yiZU3jP5bEdtJ7DxX26NhIEdjIuMBog-8OcfL6JTr7MfEutOZBFg-_iBYQ8jx5c26VUrSHYyaM"
page.get(url)


def getTurnstileToken():
    for i in range(0, 15):
        print(f"try {i + 1}")
        try:
            curr_title = page.title
            if all(
                    ["just a moment" not in curr_title.lower(), "请稍候" not in curr_title]
            ):
                break

            challengeSolution = page.ele("@name=cf-turnstile-response")
            challengeWrapper = challengeSolution.parent()
            challengeIframe = challengeWrapper.shadow_root.ele("tag:iframe")
            challengeIframeBody = challengeIframe.ele("tag:body").shadow_root
            challengeButton = challengeIframeBody.ele("tag:input")
            challengeButton.click()
        except:
            pass
        time.sleep(1)
    print(page.html[:1000])


getTurnstileToken()
```

It works fine on windows, but it will block drissionpage on docker.
If there is no such problem, please run it twice.

this is a dockerfile example:

```
FROM nikolaik/python-nodejs:python3.10-nodejs20
RUN apt update && apt-get -y install libgl1-mesa-glx
WORKDIR /data/
COPY . .
RUN pip install DrissionPage
RUN apt-get update && apt-get install -y gnupg2 curl wget unzip ca-certificates

RUN curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list && \
    apt-get -y update && \
    apt-get -y install google-chrome-stable && \
    rm -rf /var/lib/apt/lists/*

CMD ["sleep", "6000"]
```

The error content is:
```
try 1
try 2
try 3
try 4
Traceback (most recent call last):
  File "/data/CDP-bug-MouseEvent-.screenX-.screenY-patcher-main/drission_demo.py", line 67, in <module>
    getTurnstileToken()
  File "/data/CDP-bug-MouseEvent-.screenX-.screenY-patcher-main/drission_demo.py", line 65, in getTurnstileToken
    print(page.html[:1000])
  File "/data/test_venv/lib/python3.10/site-packages/DrissionPage/_pages/mix_tab.py", line 62, in html
    return super(SessionPage, self).html if self._d_mode else super().html
  File "/data/test_venv/lib/python3.10/site-packages/DrissionPage/_pages/chromium_base.py", line 323, in html
    return self._run_cdp('DOM.getOuterHTML', objectId=self._root_id)['outerHTML']
  File "/data/test_venv/lib/python3.10/site-packages/DrissionPage/_pages/chromium_base.py", line 383, in _run_cdp
    return r if __ERROR__ not in r else raise_error(r, self.browser, ignore)
  File "/data/test_venv/lib/python3.10/site-packages/DrissionPage/_functions/tools.py", line 202, in raise_error
    raise r
TimeoutError: 
错误：timeout
方法：DOM.getOuterHTML
参数：{'objectId': '3240704830043702191.1.1', '_timeout': 30}
版本：4.1.0.9
超时，可能是浏览器卡了。
```

**Comment by shengchenyang** [comment]
It seems to be a problem with drissionpage. `Page.html` is blocked until an error is reported.
